# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re


class Ui_calc(object):
    def __init__(self):
        self.txt = '0'
        self.last_op=''
        self.last_num=''

    def mySignals(self):
        self.pushButton1.clicked.connect(lambda : self.btn('1'))
        self.pushButton2.clicked.connect(lambda : self.btn('2'))
        self.pushButton3.clicked.connect(lambda : self.btn('3'))
        self.pushButton4.clicked.connect(lambda : self.btn('4'))
        self.pushButton5.clicked.connect(lambda : self.btn('5'))
        self.pushButton6.clicked.connect(lambda : self.btn('6'))
        self.pushButton7.clicked.connect(lambda : self.btn('7'))
        self.pushButton8.clicked.connect(lambda : self.btn('8'))
        self.pushButton9.clicked.connect(lambda : self.btn('9'))
        self.pushButton0.clicked.connect(lambda : self.btn('0'))
        self.pushButtonPoint.clicked.connect(lambda : self.btn('.'))
        self.pushButtonPlus.clicked.connect(lambda : self.btn('+'))
        self.pushButtonMenha.clicked.connect(lambda : self.btn('-'))
        self.pushButtonTghsim.clicked.connect(lambda : self.btn('/'))
        self.pushButtonZarb.clicked.connect(lambda : self.btn('*'))
        self.pushButtonEq.clicked.connect(self.btnEq)

    def btn(self , K):
        if self.txt[-1] in '+-/*' and  K in '+-/*' :
            self.txt = self.txt[:-1] + K
        elif K == '.':
            lastnum=re.split(r'[+*/-]', self.txt)
            if lastnum[-1].count('.') == 0:
                self.txt+=K
        else:
            if self.txt == '0' and K not in '+-/*':
                self.txt = K
            else:
                self.txt += K    
        self.lineEdit.setText(self.txt)

    def btnEq(self):
        if any(operator in self.txt for operator in "+-*/"):    
            last_operator=re.findall(r'[+*/-]',self.txt )
            last_num=re.split(r'[+*/-]', self.txt)
            self.last_num=last_num[-1]
            self.last_op=last_operator[-1]
        elif self.last_op and self.last_num:
            self.txt += self.last_op
            self.txt += self.last_num
        answer = eval(self.txt)
        self.txt = str(answer)
        self.lineEdit.setText(self.txt)

    def setupUi(self, calc):
        with open ('style.css') as f:
            mys=f.read()
        calc.setObjectName("calc")
        calc.resize(278, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(calc.sizePolicy().hasHeightForWidth())
        calc.setSizePolicy(sizePolicy)
        calc.setMinimumSize(QtCore.QSize(200, 300))
        calc.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        calc.setFont(font)
        calc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit = QtWidgets.QLineEdit(calc)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 241, 31))
        self.lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit.setObjectName("lineEdit")
        self.layoutWidget = QtWidgets.QWidget(calc)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 241, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton7 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton7.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton7.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout.addWidget(self.pushButton7, 0, 0, 1, 1)
        self.pushButton8 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton8.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout.addWidget(self.pushButton8, 0, 1, 1, 1)
        self.pushButton9 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton9.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton9.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton9.setObjectName("pushButton9")
        self.gridLayout.addWidget(self.pushButton9, 0, 2, 1, 1)
        self.pushButtonZarb = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonZarb.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonZarb.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonZarb.setObjectName("pushButtonZarb")
        self.gridLayout.addWidget(self.pushButtonZarb, 0, 3, 1, 1)
        self.pushButton4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton4.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton4.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout.addWidget(self.pushButton4, 1, 0, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton5.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout.addWidget(self.pushButton5, 1, 1, 1, 1)
        self.pushButton6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton6.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton6.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout.addWidget(self.pushButton6, 1, 2, 1, 1)
        self.pushButtonTghsim = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonTghsim.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonTghsim.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonTghsim.setObjectName("pushButtonTghsim")
        self.gridLayout.addWidget(self.pushButtonTghsim, 1, 3, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton1.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton1.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 2, 0, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton2.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout.addWidget(self.pushButton2, 2, 1, 1, 1)
        self.pushButton3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton3.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout.addWidget(self.pushButton3, 2, 2, 1, 1)
        self.pushButtonMenha = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMenha.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonMenha.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonMenha.setObjectName("pushButtonMenha")
        self.gridLayout.addWidget(self.pushButtonMenha, 2, 3, 1, 1)
        self.pushButton0 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton0.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton0.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton0.setObjectName("pushButton0")
        self.gridLayout.addWidget(self.pushButton0, 3, 1, 1, 1)
        self.pushButtonEq = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonEq.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonEq.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonEq.setObjectName("pushButtonEq")
        self.gridLayout.addWidget(self.pushButtonEq, 3, 2, 1, 1)
        self.pushButtonPlus = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonPlus.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonPlus.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonPlus.setObjectName("pushButtonPlus")
        self.gridLayout.addWidget(self.pushButtonPlus, 3, 3, 1, 1)
        self.pushButtonPoint = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonPoint.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonPoint.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonPoint.setObjectName("pushButtonPoint")
        self.gridLayout.addWidget(self.pushButtonPoint, 3, 0, 1, 1)
        calc.setStyleSheet(mys)

        self.retranslateUi(calc)
        QtCore.QMetaObject.connectSlotsByName(calc)
        self.mySignals()

    def retranslateUi(self, calc):
        _translate = QtCore.QCoreApplication.translate
        calc.setWindowTitle(_translate("calc", "My Calculator"))
        self.lineEdit.setText(_translate("calc", "0"))
        self.pushButton7.setText(_translate("calc", "7"))
        self.pushButton8.setText(_translate("calc", "8"))
        self.pushButton9.setText(_translate("calc", "9"))
        self.pushButtonZarb.setText(_translate("calc", "*"))
        self.pushButton4.setText(_translate("calc", "4"))
        self.pushButton5.setText(_translate("calc", "5"))
        self.pushButton6.setText(_translate("calc", "6"))
        self.pushButtonTghsim.setText(_translate("calc", "/"))
        self.pushButton1.setText(_translate("calc", "1"))
        self.pushButton2.setText(_translate("calc", "2"))
        self.pushButton3.setText(_translate("calc", "3"))
        self.pushButtonMenha.setText(_translate("calc", "-"))
        self.pushButton0.setText(_translate("calc", "0"))
        self.pushButtonEq.setText(_translate("calc", "="))
        self.pushButtonPlus.setText(_translate("calc", "+"))
        self.pushButtonPoint.setText(_translate("calc", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calc = QtWidgets.QWidget()
    ui = Ui_calc()
    ui.setupUi(calc)
    calc.show()
    sys.exit(app.exec_())
